let map = [	[CLU, CRU, EMP, EMP, EMP, EMP, EMP, EMP, EMP, EMP, EMP, EMP, EMP, EMP, EMP, EMP],
		   	[CLD, RWL, EMP, EMP, EMP, EMP, EMP, EMP, EMP, EMP, EMP, EMP, EMP, EMP, EMP, EMP],
			[EMP, QRV, EMP, EMP, EMP, EMP, EMP, EMP, EMP, EMP, EMP, EMP, EMP, EMP, EMP, EMP],
			[EMP, CLD, UWL, UWL, CRU, EMP, EMP, EMP, EMP, EMP, EMP, EMP, EMP, EMP, EMP, EMP],
			[EMP, EMP, LWL, GRD, RWL, EMP, EMP, EMP, CLU, UWL, QRH, QRH, CRU, EMP, EMP, EMP],
			[EMP, EMP, CLD, DWL, RWL, EMP, EMP, EMP, LWL, RWL, EMP, EMP, QRV, EMP, EMP, EMP],
			[EMP, EMP, EMP, EMP, CLD, QRH, QRH, QRH, GRD, GRD, QRH, QRH, RWL, EMP, EMP, EMP],
			[EMP, EMP, EMP, EMP, EMP, EMP, EMP, EMP, LWL, RWL, EMP, EMP, QRV, EMP, EMP, EMP],
			[EMP, EMP, EMP, EMP, EMP, EMP, EMP, EMP, CLD, DWL, QRH, QRH, CRD, EMP, EMP, EMP]];